import { redirect } from "next/navigation";
import type { NextRequest } from "next/server";
import type { EmailOtpType } from "@supabase/supabase-js";

import { createUserClient } from "@/lib/portal/supabase/server";

const OTP_TYPES: readonly EmailOtpType[] = [
  "invite",
  "magiclink",
  "recovery",
  "email",
  "signup",
];

/** Only ever bounce to portal-internal destinations. */
function safeNext(raw: string | null): string {
  if (raw && raw.startsWith("/portal") && !raw.startsWith("//")) return raw;
  return "/portal";
}

/**
 * Lands invite and sign-in links generated by the invite service
 * (`?token_hash=…&type=…`). Verifying the OTP sets the session cookies; the
 * user continues to set-password (invites) or the dashboard.
 */
export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const tokenHash = searchParams.get("token_hash");
  const rawType = searchParams.get("type") as EmailOtpType | null;
  const next = safeNext(searchParams.get("next"));

  if (tokenHash && rawType && OTP_TYPES.includes(rawType)) {
    const supabase = await createUserClient();
    const { error } = await supabase.auth.verifyOtp({ type: rawType, token_hash: tokenHash });
    if (!error) redirect(next);
    console.error("portal.auth.confirm_failed", error.message);
  }

  redirect("/portal/login?error=link");
}
